# Generated by Django 5.2.7 on 2025-10-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_giocatore_1', models.IntegerField()),
                ('punteggio_giocatore_2', models.IntegerField()),
                ('voto_giocatore_1', models.IntegerField(blank=True, null=True)),
                ('voto_giocatore_2', models.IntegerField(blank=True, null=True)),
                ('data_salvataggio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
